### ISSUE TITLE
Font Color?

### ISSUE THREAD

**Issue by RaceNJason** [ibz0q/better-moment-card#10]
This was just what I was looking for. The only thing I saw that could enhance this just a little more (especially for those viewers who use a dark background and black text color doesn't work well with that) is to be able to change the font color. Basically a font-color:blue option for example would be terrific.

Although I haven't tried it yet...it's possible that card-mod might work to change the font color in this. Still, it would be more convenient to be able to do it natively.

**Comment by ibz0q** [comment]
This is possible natively:

`type: custom:better-moment-card
parentStyle: > 
  color:blue;
moment:
  - format: HH:mm:ss`

This style is applied to the root container. You can individually apply a style to each "moment" like so:

`type: custom:better-moment-card
moment:
  - format: HH:mm:ss
    parentStyle: |
      color:blue;
  - format: cccc, dd MMMM
    parentStyle: |
      color:green;`

The plugin intentionally leaves everything unstyled, applying some styling is expected.

**Comment by RaceNJason** [comment]
Ah...I didn't know I could do that. It certainly would've been helpful in other cards if they respond to the same parentStyle: code. I've been using card-mod to do that (btw, card-mod also works in modifying the font color) but will now try this beforehand. Anyway, thanks for the info, it is helpful with more than just your card (for me at least).

**Comment by ibz0q** [comment]
Check the DOM tree out, depending on where you wish to style. E.g. background-color, card mod would be necessary. You could use purely card mod but accessing each element is a bit difficult. That's why parentStyle exist. There's really no right or wrong way.
