### ISSUE TITLE
Animated background 

### ISSUE THREAD

**Issue by swas** [ibz0q/better-moment-card#11]
Hello!

It's possible to get CSS for the animated background of the presentation gif? 😁

![live-preview](https://github.com/user-attachments/assets/2c0f0740-24d1-4f51-8b24-e9edec7e7edf)

**Comment by ibz0q** [comment]
@swas It's using a plugin I made called lovelace-bg-animation.. works best with transparent themes. I have not added to HACs but might do submit it if there's interest from other people. So far I have not shared it with anyone.

Check it out https://github.com/ibz0q/lovelace-bg-animation

```
- id: animation.63.green-circuit
- id: animation.53.stars
- id: animation.47.color-trails
- id: animation.21.noise-abstraction
- id: animation.24.trapped-gradient
```

**Comment by ibz0q** [comment]
@swas It's uses a plugin I made called lovelace-bg-animation, works best with transparent themes. I have not added to HACs yet but might if there's interest from others. So far I have not shared it with anyone from Home assistant community you're first :)

https://github.com/ibz0q/lovelace-bg-animation

Playlist:
```
- id: animation.63.green-circuit
- id: animation.53.stars
- id: animation.47.color-trails
- id: animation.21.noise-abstraction
- id: animation.24.trapped-gradient
```

**Comment by swas** [comment]
I'm amazed by the animations. I'm testing it out.
It's a pity it's a secret project 😎

**Comment by ibz0q** [comment]
I'd like to add more and finish some of the features so users can customize an animation to their preference (slow, fast etc). Feel free to add feedback in the repo.
