### ISSUE TITLE
How to decrease vertical size?

### ISSUE THREAD

**Issue by drshajul** [ibz0q/better-moment-card#7]
See the empty space below the card. How to fix that?
https://github.com/user-attachments/assets/60b71bb9-2b5d-425c-99cc-4f392204b661

**Comment by ibz0q** [comment]
Can you provide me your configuration + Theme you are using.

**Comment by drshajul** [comment]
I am using the new sections layout.. solved the issue with
`layout_options:
  grid_columns: 4
  grid_rows: null`

**Comment by ibz0q** [comment]
Great. Sections code was added in the last release, I will add a note on overriding the code.

https://github.com/ibz0q/better-moment-card/blob/9a7e7ff3607f7fa9991cb0a278c58db1b3f916db/src/better-moment-card.js#L50
