### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by BerserkerRudi** [ibz0q/better-moment-card#8]
I found no way to display Countryflags like in your example with SA and BE, how can i add this?
With "<strong>🇧🇪 Brussels</strong>" i get no Flag, just "BE"

**Comment by ibz0q** [comment]
Likely to be your browser, the browser used in the screenshot is Firefox. Chrome and Edge use system fonts and afaik do not always display emojis in a reliable way. You could consider installing the font on the OS or use a different browser.
